### ISSUE TITLE
Model inputs

### ISSUE THREAD

**Issue by kizunasunhy** [lyutyuh/ASP#2]
Hello, I try to understand what's going on here in the model. So for the NER task, basically the input of the model consists these:
```
'input_ids',
'input_mask',
'to_copy_ids',
'target_ids',
'target_mask',
'action_labels',
'ent_indices',
'ent_types'
```
But seems like the model doesn't use 'ent_indices' and 'ent_types' during training. And for 'action_labels', it will always create a cumsum for 0 to (seq_len-1) no matter what 'action_labels' really is. So we got the brackets and [copy] inside 'target_ids', I could understand that but how could the model identify the entity type in NER task?
Thank you

**Comment by lyutyuh** [comment]
Hi! 
Yes, `ent_indices` and `ent_types` are not directly used during training. Instead, we pass a parameter `lr_pair_flag` as the label for training. 
`lr_pair_flag` is of shape `target_len, num_l_brackets, num_class`. When the entry `lr_pair_flag[i,j,k] == 1`, it indicates the `i`-th token is a right bracket that pairs with the `j`-th left bracket, and the entity type is `k`.

**Comment by kizunasunhy** [comment]
> 

I see. So for inference the model will output a tensor with same size to `lr_pair_flag` and be converted to `to_copy_ids`, `decoder_pairing` and `decoder_typing` right?

**Comment by lyutyuh** [comment]
No. Since decoding is done step-by-step, we get `decoder_pairing`, `decoder_typing` directly at each step.
It's not necessary to get `lr_pair_flag` during decoding.

**Comment by kizunasunhy** [comment]
> No. Since decoding is done step-by-step, we get `decoder_pairing`, `decoder_typing` directly at each step.
> 
> It's not necessary to get `lr_pair_flag` during decoding.

Got it thanks!
