### ISSUE TITLE
Issue with installing Apex. Any option to run code without it?

### ISSUE THREAD

**Issue by shicode** [lyutyuh/ASP#5]
Thanks for the code! It's a really interesting idea! 

However, I'm trying to run the NER pipeline as-is using the given commands but I'm unable to do so due to some issues installing apex. Would it be possible to provide an option to run the code without using apex?

**Comment by Hubotcoder** [comment]
That has also bothered me for a long time. It's not easy to install apex of right version in Windows 10 and use it without a GPU.

**Comment by shicode** [comment]
That worked! Thank you!
